### PR TITLE
Update vendored Versioneer from 0.18 to 0.29

### PR DESCRIPTION
**Pull request by m-aciek**
* installed the new Versioneer (pip install -U versioneer or equivalent)
* re-runned `versioneer install --vendor` in the local source tree, to replace `transifex/_version.py`
* committed all changed files

As specified in the [guide](https://github.com/python-versioneer/python-versioneer/#updating-versioneer) (no changes to configuration were required).

Refs #106.

### CODE REVIEW

**Comment by m-aciek** [comment]
I replaced "closes" keyword with "refs" not to close #106 with this PR merged.

It looks like the pins are used only in CI and for local development, so it should be fine to pin it to the latest requests version for reproducible CI. It's not a strong opinion though.

**Comment by nbasili** [comment]
@m-aciek You will need to sign (only once) the [Transifex CLA](https://developers.transifex.com/docs/contributing) before we can merge this PR, per our [Contributing guidelines](https://github.com/transifex/transifex-python/blob/devel/CONTRIBUTING.md).

As soon as this happens, I can merge this PR. And thank you for contributing to this repo 🙏

**Comment by nbasili** [comment]
Hey @m-aciek, we have fixed the `requests` lib issue on `devel` branch. Can you please rebase?

Also did you manage to get the CLA signed?

**Comment by m-aciek** [comment]
Hey @nbasili, I've pushed the rebased changes. Also a few minutes ago I've sent the singed CLA.

**Review by nbasili — APPROVED** [review]

**Pull request merged**
